head:
    prefix: detail
    label: I18N_OPENXPKI_UI_WORKFLOW_TYPE_REPORT_DETAIL_LABEL
    description: I18N_OPENXPKI_UI_WORKFLOW_TYPE_REPORT_DETAIL_DESC
    persister: Volatile

state:
    INITIAL:
        action:
          - initialize > GENERATE

    GENERATE:
        autorun: 1
        action:
          - generate > SUCCESS


    SUCCESS:
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_REPORT_DETAIL_SUCCESS_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_REPORT_DETAIL_SUCCESS_DESC
        output: 
          - valid_at
          - total_count
          - report_filename

action:
    initialize:
        class: OpenXPKI::Server::Workflow::Activity::Noop
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_REPORT_DETAIL_INITIALIZE_LABEL
        input:
          - valid_at

    generate:
        class: OpenXPKI::Server::Workflow::Activity::Reports::Detail
        param:
            valid_at: 20150701
            target_umask: 0644
  
field:
    valid_at:
        name: valid_at
        label: I18N_OPENXPKI_UI_WORKFLOW_REPORT_FIELD_VALID_AT_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_REPORT_FIELD_VALID_AT_DESCRIPTION
        required: 0
        type: datetime
        format: timestamp
        default: now

    total_count:
        name: total_count
        label: I18N_OPENXPKI_UI_WORKFLOW_REPORT_FIELD_TOTAL_COUNT

    report_filename:
        name: report_filename
        format: download/text/csv
 

acl:
    CA Operator:
        creator: any

    RA Operator:
        creator: any
        fail: 1
        resume: 1
        wakeup: 1

    System:
        creator: any

