head:
    prefix: detail
    label: I18N_OPENXPKI_UI_WORKFLOW_TYPE_REPORT_DETAIL_LABEL
    description: I18N_OPENXPKI_UI_WORKFLOW_TYPE_REPORT_DETAIL_DESC
    persister: Volatile

state:
    INITIAL:
        action:
          - initialize > GENERATE

    GENERATE:
        autorun: 1
        action:
          - generate > SUCCESS


    SUCCESS:
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_REPORT_DETAIL_SUCCESS_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_REPORT_DETAIL_SUCCESS_DESC
        output: 
          - valid_at
          - total_count
          - report_filename

action:
    initialize:
        class: OpenXPKI::Server::Workflow::Activity::Noop
        label: I18N_OPENXPKI_UI_WORKFLOW_ACTION_REPORT_DETAIL_INITIALIZE_LABEL
        input:
          - valid_at
          - target_filename
          - report_config

    generate:
        class: OpenXPKI::Server::Workflow::Activity::Reports::Detail
        param:            
            target_umask: 0644
            _map_target_filename: >
                [% IF context.target_filename %][% context.target_filename %]
                [% ELSE %]pki report [% USE date(format='%Y-%m-%dT%H:%M:%S') %][% date.format( context.valid_at ) %].csv[% END %]
            target_dir: /tmp
            _map_report_config: $report_config
  
field:
    valid_at:
        name: valid_at
        label: I18N_OPENXPKI_UI_WORKFLOW_REPORT_FIELD_VALID_AT_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_REPORT_FIELD_VALID_AT_DESCRIPTION
        required: 0
        type: datetime
        format: timestamp
        default: now

    total_count:
        name: total_count
        label: I18N_OPENXPKI_UI_WORKFLOW_REPORT_FIELD_TOTAL_COUNT

    report_filename:
        name: report_filename
        format: download/text/csv
        
    target_filename:
        name: target_filename
        type: server 
        required: 0

    report_config:
        name: report_config
        type: server
        required: 0

acl:
    CA Operator:
        creator: any

    RA Operator:
        creator: any
        fail: 1
        resume: 1
        wakeup: 1

    System:
        creator: any

