head:
    prefix: scfp
    label: I18N_OPENXPKI_UI_WORKFLOW_TYPE_SMARTCARD_FETCH_PUK_LABEL
    description: I18N_OPENXPKI_UI_WORKFLOW_TYPE_SMARTCARD_FETCH_PUK_DESC

state:
    FAILURE: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_FAILURE_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_FAILURE_DESC

    INITIAL: 
        action: 
          - initialize fetch_puk > MAIN

    MAIN: 
        action: 
          - puk_fetch_err > FAILURE
          - ack_fetch_puk > SUCCESS

    SUCCESS: 
        label: I18N_OPENXPKI_UI_WORKFLOW_STATE_SUCCESS_LABEL
        description: I18N_OPENXPKI_UI_WORKFLOW_STATE_SUCCESS_DESC


action:
    ack_fetch_puk: 
        class: Workflow::Action::Null

    fetch_puk: 
        class: OpenXPKI::Server::Workflow::Activity::SmartCard::FetchPUK
        param: 
            ds_default_value: $smartcard_default_puk
            ds_key_param: token_id
            ds_namespace: smartcard.puk
            ds_value_param: _puk

    initialize: 
        class: Workflow::Action::Null
        input: 
          - token_id

    puk_fetch_err: 
        class: Workflow::Action::Null
        input: 
          - error_reason

field:
    error_reason: 
        name: error_reason
        required: 1
        type: text

    token_id: 
        name: token_id
        type: text
        required: 0


acl:
    SmartCard:
        creator: any
 

